apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pdf-analyzer-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hetzner-volume
  resources:
    requests:
      storage: 10Gi
