apiVersion: v1
kind: PersistentVolume
metadata:
  name: pdf-analyzer-pv
  labels:
    type: hetzner-volume-pdfs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hetzner-volume
  csi:
    driver: csi.hetzner.cloud
    volumeHandle: "103823462"
    fsType: ext4
